services:
  - type: web
    name: lucky-barber
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"

    plan: free

    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false   # La agregar√°s manualmente en el panel de Render

    autoDeploy: true