[google]
type = "service_account"
project_id = "barberiaapp-478106"
private_key_id = "900490d9c45bc93156aad58c015a252770b950fe"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyl9ijlDIRGleD
HqcBfP7yHUv/9rjP8g0/ohoHDVWJGK8humdTkPalD6hqu/cWNVV0TRPxg8Oj1gmN
/GFg+u74hOqOmZinCrQyzSf8DP2QVM4CpHBOKjwZ3sJAubvlnTW8xaCOpVaJMFzr
1xnlqWdqJsJIBjtx4EUi7GJe7Qr5EQm4ZdrM+jTMp1JxLYV5Fpl24OD6oniFd0Tw
8/XkdJAdNiPH4+Ljhhu3QBLvxHGnZF13kv64QLvd9NnFip5S17IZzHP4j9jj+h/8
3wb2W4uv6pqZ909Y6Ml1Jqr9LiytPf3c+KpiZS+VaaT2OSMQnzcPBd9I1kwbK6Q7
YwjQzxm7AgMBAAECggEADeTPR0aPsJHujfZUAsMhKF/MGlEs5oyLqFApmzPX3C8N
7N9OC4vDDGtP7GHMIq+qgr4+V3MrRLMxkhi40K0k6zOX9dkQLaqhAzS/sBWoolJe
poj5bbNOcqrITPXGHuJgnFt5lq9ZMJoRGI3m512K/JCgW68Ub9MFPebK7lydlmuy
DpZ2dR1rMSw0oHjJ7H0+O1Y0fEb6JzPPvPe4EYWDXY79yGS+yljRM8tNL+UXbKaT
o8wi1Bxw5dAp80Rx1L6W3izngSBXuUwnOuRv07gtFcvrAlSIRSmZqrl5+TCZ+W0w
AU3yt46L7VegBTo3RyXE522y5uRbPQSUw4KwYpKz7QKBgQDlUCiXVAUfWC55D49P
LKGw9eSekAZclJD9+Yl80CW6PI1Gepfrf3lk3fssiL7/D0lJ0wbSXzbZ3+zc5JT/
5NLABDLfcQa+d5dwhNLR7D3ND3F6/SZbFAGhB3d7lU+UGgsIVDYaf4m0ATTefMp/
75hGy54fflSEU8rh4WP4xG8WfwKBgQDHYJs0rnaWV3SQ8XnwpGruJggX0D0J1Lum
tFyJowc3IeQFU2VdI3KwpF8vs0178kJgknUyCMnDWdaxUJvJZpeUrczpaMoCHUJm
AhgSL3KiyUtdtf6w86Sph4K2qlhMgRCX3cTyLHQGKpwxAQowriRvT9o2nEZf2UMY
dWODxWw2xQKBgHCeT3ESiHl+W0SFScJ+juJTwPXGkflB1XuF4+nyZ7TxLAjjCF1V
+454HnUeq36kSUACbaU/sbaK7M8HS83o2UAIT9vArKk6HpvZ/5etSCS/YuIeFYpB
ZxNokVuWVsDLkYODqBaXcE+BEC/8ZY8zYjvSoFOjPWrHpCoPAYQZJN2NAoGAPJwm
sp4y2MNfYUy3aCtjgmA3Z53bYGi2XxhHZWQVJnJ8Eg5nKyhCjmZ5tVOJw5tDCH6d
eAdp5qQh+ydpJJG2lPE88Nv1RS1F6SLL1INuEwSkj6lq8rounYbfes5QJ3m45KH7
ZC+VWeaMMu2A/omB9ADPcniRgEPY/M964C0dF40CgYEAybJfvG2N9OIzTKylvASD
SDWnzMbFSmhTE2PiSWErslJSk3Z4KD0fxffvK847VDkd5lUA456r9MFOIbdd6c55
AtKbERYLUuKMCQNIXht5GD8Gqd+9k75Ut/MWGqF2aEP3dWRJ92tfjE4CKxItw6hy
97Cm8m4OcQzQYjazCaf1708=
-----END PRIVATE KEY-----"""
client_email = "barberia-service-account@barberiaapp-478106.iam.gserviceaccount.com"
client_id = "106200147850566032060"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/barberia-service-account%40barberiaapp-478106.iam.gserviceaccount.com"